/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh
    button: THREE.Mesh
    tip: THREE.Mesh
    grafitti: THREE.Mesh
    clipping: THREE.Mesh
    Cubo: THREE.Mesh
  }
  materials: {
    plastic: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    grafitti: THREE.MeshStandardMaterial
    ['Materiais.003']: THREE.MeshStandardMaterial
  }
}

type ActionName =
  | 'bodyAction'
  | 'buttonAction'
  | 'tipAction'
  | 'grafittiAction'
  | 'clippingAction'
  | 'CuboAction'
  | 'Spot.001Action'
  | 'AreaAction'
  | 'Area.001Action'
  | 'Point.001Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/pen-draco.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="body"
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.plastic}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        name="button"
        castShadow
        receiveShadow
        geometry={nodes.button.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        name="tip"
        castShadow
        receiveShadow
        geometry={nodes.tip.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        name="grafitti"
        castShadow
        receiveShadow
        geometry={nodes.grafitti.geometry}
        material={materials.grafitti}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        name="clipping"
        castShadow
        receiveShadow
        geometry={nodes.clipping.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        name="Cubo"
        castShadow
        receiveShadow
        geometry={nodes.Cubo.geometry}
        material={materials['Materiais.003']}
        position={[0, 0, 6]}
        scale={[9.9, 9.9, 9.9]}
      />
    </group>
  )
}

useGLTF.preload('/pen-draco.glb')
