/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh
    button: THREE.Mesh
    tip: THREE.Mesh
    grafitti: THREE.Mesh
    clipping: THREE.Mesh
    Plano: THREE.Mesh
    Plano001: THREE.Mesh
  }
  materials: {
    plastic: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    grafitti: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/pen-draco.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.01, 13.82]}>
        <pointLight intensity={500} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.03, 5.88, 0.11]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={1000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.03, 5.88, 9.62]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={1000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh
        geometry={nodes.body.geometry}
        material={materials.plastic}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.button.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.tip.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.grafitti.geometry}
        material={materials.grafitti}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.clipping.geometry}
        material={materials.metal}
        rotation={[0, 0, -Math.PI / 4]}
        scale={[-0.21, -0.21, -0.21]}
      />
      <mesh
        geometry={nodes.Plano.geometry}
        material={materials['default']}
        position={[0, -1.37, -2.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[10.79, 10.79, 10.79]}
      />
      <mesh
        geometry={nodes.Plano001.geometry}
        material={materials['default']}
        position={[-0.02, -8.57, 0]}
        scale={[8.64, 8.64, 8.64]}
      />
    </group>
  )
}

useGLTF.preload('/pen-draco.glb')
